# Generated by Django 5.0.2 on 2024-03-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
